### ISSUE TITLE
Zooming in.

### ISSUE THREAD

**Issue by jmevalentin** [warpdesign/pcx-js#1]
I'm not sure this is directly related to this library, but can you assist in providing an example of how to zoom into the loaded image?

**Comment by warpdesign** [comment]
I am closing the issue since it's not related to pcx-js.

**Comment by warpdesign** [comment]
If you are using pcx-js into the browser you may use drawImage canvas method to zoom into the image.

By using a destWidth/Height greater than source width/height will scale the image:

```
context.drawImage(img, sx, sy,s width, sheight, x, y ,width, height);
```

**Comment by jmevalentin** [comment]
Hi and thank you for your assistance. Also, thank you for this great library.  I am actually familiar with the drawImage() approach and it comes in handy, but the goal is a little more involved so I though thought I would share it as well as my progress. I am creating a pcx file editor to change not only colors of pixels, but I also to have to add an array of data to some pixels, then save the file with this data or at least the color changes and if the data array can't be saved to the pcx file directly, then I would export that content to another file for processing by another system. This is what I hope your library and the canvas API will help me achieve.

What I've done is combine the PCX import with the help of your library and the canvas context scale and transform like this:
`ctx.clearRect(0, 0, cw, ch);`
`  ctx.translate(panX / 2, panY / 2);`
`  ctx.scale(scaleFactor, scaleFactor);`
`  ctx.drawImage(sourcepic,0,0);`
Then I set the scaleFactor via button event to pan in or out. The issue is I need to keep a copy of the image I'm editing so I'm using canvas.toDataURL() to get the loaded image and store it in an image object which I then reload. 

The goal of zooming is to present the user with a clearer picture of the image pixels for easy selection and subsequent attribute assignments (color and data arrays).

Can you tell me if this whole approach is the most practical or is there a better way to achieve the goal of editing a pcx file and adding data (or at least creating a separate file with an array of data points and arbitrary data)?

Thanks again for your help.
