### ISSUE TITLE
Jquery calls

### ISSUE THREAD

**Issue by jmevalentin** [warpdesign/pcx-js#2]
I've attempted to call the decode function from a jquery which I'm using to zoom, and I can't seem to figure out the proper way to formate the options to pass to the function. Can you please advise?

**Comment by warpdesign** [comment]
Could you provide an example source code? Are you getting any errors?

**Comment by jmevalentin** [comment]
Hi, I gave up, but what I was trying was calling decodePCX() function in jquery and it seems that I don't know how to convert the options param to a properly formatted canvas object.  I'm using a file loader which calls a loadFromSelector() as follows:
```
function loadFromSelector() {
    decodePCX({ canvas: document.getElementById('canvas') });
    if(typeof(ctx) == 'undefined') {
        ctx = document.getElementById('canvas').getContext("2d");
    }
}

function decodePCX(options) {
    var canvas = options.canvas,
        context = canvas.getContext('2d');
    var loadedfile =
        initBrowserFileReader.loadFile(document.getElementById("gfile").files[0]).then((buffer) => {
            var pcx = new PCX(buffer);
            var pcxData = pcx.decode(context);
            initBrowserFileReader.render(context, pcxData);
        }).catch (function(error) {
        console.log("Error reading PCX File: ", error);
        });
} 
```
Then, in the initBrowserFileReader render call, I do the following
``` 
   document.getElementById("sourcepic").src = ctx.canvas.toDataURL("image/png");
   sourcepic.src = document.getElementById("sourcepic").src; 
```

This provides me with a source object to redraw the image after each zoom or pan action. I'm actually still working on that but I have some basic functionality working. 

When I tried moving the loadFromSelector() function to a jquery assignment and then moved the decodePCX function into a $(document).ready function, I would get the error `Uncaught ReferenceError: canvas is not defined` when calling `canvas.getContext("2d");`, so it is not recognizing the canvas object which all other jquery code I'm calling recognizes. I am using that object for redraws of the canvas successfully. 

If you have any ideas or a better approach, I'd really appreciate your advice. 

Thanks again.

**Comment by warpdesign** [comment]
Do you have the *full source code* (with html) ? It seems like your canvas doesn't exists at the time `decodePCX` is called, so `document.getElementById('canvas')` returns `null`.

That would explain the error you are getting, which doesn't seem related to pcx-js.

**Comment by jmevalentin** [comment]
Well, currently the code works if I leave the functions above outside of jQuery, and since I tried calling from within jquery $(document).ready, I thought it should work since the canvas element exists. I could have made a mistake, so I'll have to try it again to see what I did wrong.

**Comment by warpdesign** [comment]
I close the issue as it's doesn't seem related to pcx-js.
