### ISSUE TITLE
Encoding capabilities

### ISSUE THREAD

**Issue by jmevalentin** [warpdesign/pcx-js#3]
Hello, 

I have figured out some of my other issues and am working on editing of the canvas. I next need to save the edits back out to the PCX format. Can you please advise on how to do that, as I have now noticed that your library is mainly for decoding and importing of the file to the canvas.

Once again thanks for the great library.

**Comment by warpdesign** [comment]
I close the issue since it's out of pcx-js's scope: pcx-js is only decodes pcx files.

You may have a look at [FileSaver.js](https://github.com/eligrey/FileSaver.js) in order to save a file from JavaScript. This won't encode the file as PCX for you though.

**Comment by jmevalentin** [comment]
Ok, would you be willing to advise on "reversing" the process of this decoder so I can create an encoder?
